name: Pixel Engine Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows10

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    # Cache Builds
    - name: Cache Build
      uses: actions/cache@v2
      with:
        path: |
          ./CorePixelEngine.Core/bin
          ./CorePixelEngine.Core/obj
          ./CorePixelEngine.Linux/bin
          ./CorePixelEngine.Linux/obj
          ./CorePixelEngine.OpenGL.Net/bin
          ./CorePixelEngine.OpenGL.Net/obj
          ./CorePixelEngine.Windows.Net/bin
          ./CorePixelEngine.Windows.Net/obj
        key: ${{ github.sha }}

    # Build Windows
    - name: Install dependencies Windows
      run: dotnet restore ./CorePixelEngine.Windows/CorePixelEngine.Windows.csproj
    - name: Build Windows
      run: dotnet build --configuration Release --no-restore ./CorePixelEngine.Windows/CorePixelEngine.Windows.csproj
    - name: Test Windows
      run: dotnet test --no-restore --verbosity normal ./CorePixelEngine.Windows/CorePixelEngine.Windows.csproj
