name: Pixel Engine Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      
    # Build Core
    - name: Install dependencies Core
      run: dotnet restore ./CorePixelEngine.Core/CorePixelEngine.Core.csproj
    - name: Build Core
      run: dotnet build --configuration Release --no-restore ./CorePixelEngine.Core/CorePixelEngine.Core.csproj
    - name: Test Core
      run: dotnet test --no-restore --verbosity normal ./CorePixelEngine.Core/CorePixelEngine.Core.csproj
      
    # Build Linux
    - name: Install dependencies Linux
      run: dotnet restore ./CorePixelEngine.Linux/CorePixelEngine.Linux.csproj
    - name: Build Linux
      run: dotnet build --configuration Release --no-restore ./CorePixelEngine.Linux/CorePixelEngine.Linux.csproj
    - name: Test Linux
      run: dotnet test --no-restore --verbosity normal ./CorePixelEngine.Linux/CorePixelEngine.Linux.csproj
